name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
            
#       - name: Checkout Repo
#         uses: actions/checkout@master
#         with:
#           submodules: true
#       - name: Publish Site
#         uses: chabad360/hugo-gh-pages@master
#         with:
#           GITHUBTOKEN: ${{ secrets.PERSONAL_TOKEN }}
